import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Injectable } from '@angular/core';
import { Jobsite } from '../models/jobsite';

@Injectable({
  providedIn: 'root'
})
export class InMemoryDataService implements InMemoryDbService {

  // TODO Change the dummy data below with data from a service (HTTP/API call).

  createDb() {
    const jobsites: any[] = [
      { 
        id: 1, 
        jobsitename: 'Kelvingroove Park', 
        jobsitestreet: 'Street A',
        number: '24', 
        country: {
          name: "Mexico", 
          value: "MX", 
          selected: false
        }, 
        state: { 
          name: "Alabama", 
          value: "AL", 
          selected: false 
        },
        city: 'Monterrey',
        zipcode: '500100',
        foreman: { 
          name: 'Donatello' , 
          value: 'F1', 
          selected: false 
        },
        product: [
          { 
            id: 0,
            name: 'Limerock Base', 
            value: 'P1', 
            selected: false,
            progress: 10,
            color:'#1B5E20',
            quantity: 100,
            totalloads: 5,
            collectedloads : 1,
            remainingloads: 4,
            collectedquantity: 20,
            remainingquantity: 80
          },
          {
            id: 1,
            name: '407 Rock' , 
            value: 'P3', 
            selected: false,
            progress: 40,
            color:'#01579B',
            quantity: 350,
            totalloads: 17,
            collectedloads : 9,
            remainingloads: 8,
            collectedquantity: 190,
            remainingquantity: 160 
          },
          {
            id: 2,
            name: 'Fill Screening' , 
            value: 'P13', 
            selected: false,
            progress: 30,
            color:'#01579B',
            quantity: 350,
            totalloads: 17,
            collectedloads : 9,
            remainingloads: 8,
            collectedquantity: 190,
            remainingquantity: 160 
          }
        ],
        totalquantity: 450,
        totaljobsitecollectedloads: 16,
        totaljobsiteloads: 30,
        totalproducts: 3,
        progress: 42 
      },
      { 
        id: 2, 
        jobsitename: 'Punta Estrella', 
        jobsitestreet: 'Street B',
        number: '52', 
        country: {
          name: "Argentina", 
          value: "AR", 
          selected: false
        }, 
        state: { 
          name: "Alabama", 
          value: "AL", 
          selected: false 
        },
        city: 'Atlantic City',
        zipcode: '900122',
        foreman: { 
          name: 'Leondardo' , 
          value: 'F2', 
          selected: false 
        },
        product: [
          { 
            id: 0,
            name: 'Limerock Base', 
            value: 'P1', 
            selected: false,
            progress: 60,
            color:'#1B5E20',
            quantity: 20,
            totalloads: 10,
            collectedloads : 5,
            remainingloads: 5,
            collectedquantity: 10,
            remainingquantity: 10
          },
          {
            id: 1,
            name: 'Fill Screening', 
            value: 'P3', 
            selected: false,
            progress: 50,
            color:'#01579B',
            quantity: 10,
            totalloads: 5,
            collectedloads : 2,
            remainingloads: 3,
            collectedquantity: 4,
            remainingquantity: 6 
          }
        ],
        totalquantity: 410,
        totaljobsitecollectedloads: 14,
        totaljobsiteloads: 20,
        totalproducts: 2,
        progress: 72
      },
      { 
        id: 3, 
        jobsitename: 'Florida St', 
        jobsitestreet: 'Street C',
        number: '12A', 
        country: {
          name: "USA", 
          value: "US", 
          selected: false
        }, 
        state: { 
          name: "Alabama", 
          value: "AL", 
          selected: false 
        },
        city: 'Beijing',
        zipcode: '101022',
        foreman: { 
          name: 'Raphaelo' , 
          value: 'F3', 
          selected: false 
        },
        product: [
          { 
            id: 0,
            name: '407 Rock', 
            value: 'P3', 
            selected: false,
            progress: 35,
            color:'#1B5E20',
            quantity: 24,
            totalloads: 12,
            collectedloads : 0,
            remainingloads: 12,
            collectedquantity: 0,
            remainingquantity: 24
          },
          { 
            id: 1,
            name: 'Fill Screening', 
            value: 'P3', 
            selected: false,
            progress: 15,
            color:'#1B5E20',
            quantity: 24,
            totalloads: 12,
            collectedloads : 0,
            remainingloads: 12,
            collectedquantity: 0,
            remainingquantity: 24
          }
        ],
        totalquantity: 206,
        totaljobsitecollectedloads: 1,
        totaljobsiteloads: 10,
        totalproducts: 2,
        progress: 10
      },
      { 
        id: 4, 
        jobsitename: 'Stonecridge North', 
        jobsitestreet: 'Street D',
        number: '12A', 
        country: {
          name: "USA", 
          value: "US", 
          selected: false
        }, 
        state: { 
          name: "Alabama", 
          value: "AL", 
          selected: false 
        },
        city: 'Beijing',
        zipcode: '101022',
        foreman: { 
          name: 'Raphaelo' , 
          value: 'F3', 
          selected: false 
        },
        product: [
          { 
            id: 0,
            name: '407 Rock', 
            value: 'P3', 
            selected: false,
            progress: 20,
            color:'#1B5E20',
            quantity: 24,
            totalloads: 12,
            collectedloads : 0,
            remainingloads: 12,
            collectedquantity: 0,
            remainingquantity: 24
          }
        ],
        totalquantity: 206,
        totaljobsitecollectedloads: 1,
        totaljobsiteloads: 10,
        totalproducts: 1,
        progress: 'OPEN',
      },
      { 
        id: 5, 
        jobsitename: 'Margain Center', 
        jobsitestreet: 'Street E',
        number: '12A', 
        country: {
          name: "USA", 
          value: "US", 
          selected: false
        }, 
        state: { 
          name: "Alabama", 
          value: "AL", 
          selected: false 
        },
        city: 'Beijing',
        zipcode: '101022',
        foreman: { 
          name: 'Raphaelo' , 
          value: 'F3', 
          selected: false 
        },
        product: [
          { 
            id: 0,
            name: '407 Rock', 
            value: 'P3', 
            selected: false,
            color:'#1B5E20',
            quantity: 24,
            totalloads: 12,
            collectedloads : 0,
            remainingloads: 12,
            collectedquantity: 0,
            remainingquantity: 24
          },
          { 
            id: 1,
            name: 'Fill Screening', 
            value: 'P3', 
            selected: false,
            color:'#1B5E20',
            quantity: 24,
            totalloads: 12,
            collectedloads : 0,
            remainingloads: 12,
            collectedquantity: 0,
            remainingquantity: 24
          }
        ],
        totalquantity: 206,
        totaljobsitecollectedloads: 1,
        totaljobsiteloads: 10,
        totalproducts: 2,
        progress: 'OPEN',
      }
    ];

    const planningstatuses = ['Pending', 'Sent'];
    const planningcolors = ['warning', 'success'];
    const plannings: any[] = [
      { 
        id: 1,
        status: 1, 
        jobsite: {
          name: "Kelvingroove Park", 
          value: "A", 
          selected: false
        }, 
        purchaseorder: '123-456-789', 
        hauler: {
          name: 'Mark Jonson',
          value: 'H1',
          selected: false
        }, 
        quarry: "Sandsolid Quarry", 
        date: null, 
        product: { 
          name: 'B20038741 - F´C250 28DIAS REV18 TMA2 DURAMAX 3201D3', 
          value: 'P1', 
          selected: false 
        }, 
        quantity: 35 
      },
      { 
        id: 2, 
        status: 1,
        jobsite: {
          name: "Punta Estrella", 
          value: "B", 
          selected: false
        }, 
        purchaseorder: '111-222-333', 
        hauler: {
          name: 'Tony Montana',
          value: 'H2',
          selected: false
        },
        quarry: "Stoneridge Quarry", 
        date: null, 
        product: { 
          name: '20038741 - F´C250 28DIAS REV18 TMA2 DURAMAX 3201D3', 
          value: 'P2', 
          selected: false 
        }, 
        quantity: 50 
      },
      { 
        id: 3, 
        status: 1,
        jobsite: {
          name: "Florida St", 
          value: "C", 
          selected: false
        }, 
        purchaseorder: '222-333-789', 
        hauler: {
          name: 'Dan the Man',
          value: 'H3',
          selected: false
        },
        quarry: "Riverbank Quarry", 
        date: null, 
        product: { 
          name: '30038741 - F´C250 28DIAS REV18 TMA2 DURAMAX 3201D3', 
          value: 'P2', 
          selected: false 
        }, 
        quantity: 70 
      },
      { 
        id: 4, 
        status: 1,
        jobsite: {
          name: "Jobsite D", 
          value: "D", 
          selected: false
        }, 
        purchaseorder: '222-444-666', 
        hauler: {
          name: 'Dan the Man',
          value: 'H3',
          selected: false
        },
        quarry: "Rockysand Quarry", 
        date: null, 
        product: { 
          name: '20038741 - F´C250 28DIAS REV18 TMA2 DURAMAX 3201D3', 
          value: 'P2', 
          selected: false 
        }, 
        quantity: 32 
      }
    ];

    const deliverystatuses = ['At quarry', 'Delivered'];
    const statuscolor = ['warning', 'success'];
    const deliveries: any[] = [
      { 
        id: 1, 
        status: 0, 
        jobsiteId: 2,
        jobsitename: 'Kelvingroove Park',
        jobsitecode: 'JSA',
        deliveryticket: '00087',
        productname: 'Limerock Base',
        productcommercialcode: '507',
        ordernumber: '1-2450-231-123',
        hauler: 'Mike Doe',
        vehicle: '1VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 29,
        status: 1,
        jobsiteId: 1,
        jobsitename: 'Kelvingroove Park',
        jobsitecode: 'JSA',
        deliveryticket: '11002',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'Jasmine Rice',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 30,
        status: 1,
        jobsiteId: 1,
        jobsitename: 'Kelvingroove Park',
        jobsitecode: 'JSA',
        deliveryticket: '02933',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'Tonny Clarke',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'10',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 2,
        status: 1,
        jobsiteId: 1,
        jobsitename: 'Kelvingroove Park',
        jobsitecode: 'JSA',
        deliveryticket: '00094',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'Summer Troy',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
   
      {
        id: 4,
        status: 0,
        jobsiteId: 2,
        jobsitename: 'Punta Estrella',
        jobsitecode: 'JSB',
        deliveryticket: '00085',
        productname: 'Limerock Base',
        productcommercialcode: '507',
        ordernumber: '1-4000-231-123',
        hauler: 'Sandy Cohen',
        vehicle: '4VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 5,
        status: 1,
        jobsiteId: 2,
        jobsitename: 'Punta Estrella',
        jobsitecode: 'JSB',
        deliveryticket: '00056',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-5000-231-123',
        hauler: 'Laurance Chuck',
        vehicle: '5VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'19.8',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      
      {
        id: 31,
        status: 0,
        jobsiteId: 1,
        jobsitename: 'Kelvingroove Park',
        jobsitecode: 'JSA',
        deliveryticket: '11234',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'Timothy Granger',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.1',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 32,
        status: 1,
        jobsiteId: 1,
        jobsitename: 'Kelvingroove Park',
        jobsitecode: 'JSA',
        deliveryticket: '32993',
        productname: 'Limerock Base',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'Seth Cohen',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.5',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 34,
        status: 1,
        jobsiteId: 1,
        jobsitename: 'Punta Estrella',
        jobsitecode: 'JSA',
        deliveryticket: '50237',
        productname: 'Limerock Base',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'Laura Silvester',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 6,
        status: 0,
        jobsiteId: 1,
        jobsitename: 'Kelvingroove Park',
        jobsitecode: 'JSC',
        deliveryticket: '00012',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-6000-231-123',
        hauler: 'Valerio Cambogea',
        vehicle: '6VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 17 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.2',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 8,
        status: 0,
        jobsiteId: 2,
        jobsitename: 'Punta Estrella',
        jobsitecode: 'JSB',
        deliveryticket: '00044',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-6000-231-123',
        hauler: 'Jim Wills',
        vehicle: '4VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 17 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.1',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 9,
        status: 0,
        jobsiteId: 1,
        jobsitename: 'Kelvingroove Park',
        jobsitecode: 'JSA',
        deliveryticket: '00031',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-6000-231-123',
        hauler: 'Sandra Barbara',
        vehicle: '4VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 17 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.55',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 10,
        status: 1,
        jobsiteId: 1,
        jobsitename: 'Kelvingroove Park',
        jobsitecode: 'JSA',
        deliveryticket: '00098',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-6000-231-123',
        hauler: 'Hailey Boston',
        vehicle: '3VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 17 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.2',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 11,
        status: 1,
        jobsiteId: 3,
        jobsitename: 'Florida St',
        jobsitecode: 'JSC',
        deliveryticket: '00275',
        productname: 'Limerock Base',
        productcommercialcode: '300',
        ordernumber: '1-6000-231-123',
        hauler: 'Sony Tullei',
        vehicle: '3VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 17 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.6',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 12,
        status: 1,
        jobsiteId: 3,
        jobsitename: 'Florida St',
        jobsitecode: 'JSB',
        deliveryticket: '00784',
        productname: 'Limerock Base',
        productcommercialcode: '300',
        ordernumber: '1-6000-231-123',
        hauler: 'Samuel V.',
        vehicle: '3VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 17 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'19.8',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 13,
        status: 1,
        jobsiteId: 3,
        jobsitename: 'Florida St',
        jobsitecode: 'JSC',
        deliveryticket: '00447',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-6000-231-123',
        hauler: 'Richard Stege',
        vehicle: '6VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 17 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.15',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 14,
        status: 1,
        jobsiteId: 3,
        jobsitename: 'Florida St',
        jobsitecode: 'JSA',
        deliveryticket: '00041',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-6000-231-123',
        hauler: 'Charlles Darwin',
        vehicle: '4VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 17 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 15,
        status: 1,
        jobsiteId: 3,
        jobsitename: 'Florida St',
        jobsitecode: 'JSA',
        deliveryticket: '00004',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-6000-231-123',
        hauler: 'Raven Claw',
        vehicle: '3VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 17 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.8',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 16,
        status: 1,
        jobsiteId: 2,
        jobsitename: 'Punta Estrella',
        jobsitecode: 'JSB',
        deliveryticket: '00218',
        productname: 'Limerock Base',
        productcommercialcode: '300',
        ordernumber: '1-6000-231-123',
        hauler: 'Tim Jordan',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 17 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.1',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 17,
        status: 1,
        jobsiteId: 2,
        jobsitename: 'Punta Estrella',
        jobsitecode: 'JSA',
        deliveryticket: '00532',
        productname: 'Limerock Base',
        productcommercialcode: '300',
        ordernumber: '1-6000-231-123',
        hauler: 'Luke Skywalker',
        vehicle: '5VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 17 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 18,
        status: 1,
        jobsiteId: 2,
        jobsitename: 'Punta Estrella',
        jobsitecode: 'JSA',
        deliveryticket: '00180',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-6000-231-123',
        hauler: 'Michelle Laur',
        vehicle: '4VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 17 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.6',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 19,
        status: 1,
        jobsiteId: 3,
        jobsitename: 'Florida St',
        jobsitecode: 'JSC',
        deliveryticket: '00155',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-6000-231-123',
        hauler: 'Anna Kolbena',
        vehicle: '1VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 17 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 20,
        status: 1,
        jobsiteId: 3,
        jobsitename: 'Florida St',
        jobsitecode: 'JSA',
        deliveryticket: '00121',
        productname: 'Limerock Base',
        productcommercialcode: '300',
        ordernumber: '1-6000-231-123',
        hauler: 'Samantha August',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 17 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 21,
        status: 1,
        jobsiteId: 2,
        jobsitename: 'Kelvingroove Park',
        jobsitecode: 'JSA',
        deliveryticket: '01094',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'Alexandra Moon',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.1',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 22,
        status: 1,
        jobsiteId: 2,
        jobsitename: 'Punta Estrella',
        jobsitecode: 'JSA',
        deliveryticket: '02941',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'Victoria South',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.3',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 23,
        status: 1,
        jobsiteId: 1,
        jobsitename: 'Kelvingroove Park',
        jobsitecode: 'JSA',
        deliveryticket: '11222',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'Jimmy Morris',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.3',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 24,
        status: 0,
        jobsiteId: 3,
        jobsitename: 'Kelvingroove Park',
        jobsitecode: 'JSA',
        deliveryticket: '20191',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'Bruce Wayne',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 25,
        status: 1,
        jobsiteId: 2,
        jobsitename: 'Kelvingroove Park',
        jobsitecode: 'JSA',
        deliveryticket: '20993',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'Alfred Rolland',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 26,
        status: 0,
        jobsiteId: 1,
        jobsitename: 'Kelvingroove Park',
        jobsitecode: 'JSA',
        deliveryticket: '66644',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'Cristal Doe',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.7',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 27,
        status: 0,
        jobsiteId: 1,
        jobsitename: 'Punta Estrella',
        jobsitecode: 'JSA',
        deliveryticket: '11245',
        productname: 'Limerock Base',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'Sonia Steam',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.14',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 28,
        status: 0,
        jobsiteId: 2,
        jobsitename: 'Kelvingroove Park',
        jobsitecode: 'JSA',
        deliveryticket: '88661',
        productname: 'Limerock Base',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'James Hallway',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.4',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 35,
        status: 1,
        jobsiteId: 3,
        jobsitename: 'Kelvingroove Park',
        jobsitecode: 'JSA',
        deliveryticket: '01840',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'Robert Orwath',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.1',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 36,
        status: 1,
        jobsiteId: 1,
        jobsitename: 'Punta Estrella',
        jobsitecode: 'JSA',
        deliveryticket: '99372',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'Harmony Granger',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 37,
        status: 1,
        jobsiteId: 2,
        jobsitename: 'Kelvingroove Park',
        jobsitecode: 'JSA',
        deliveryticket: '11233',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'Frank Joseph',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.4',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 38,
        status: 1,
        jobsiteId: 1,
        jobsitename: 'Kelvingroove Park',
        jobsitecode: 'JSA',
        deliveryticket: '23411',
        productname: 'Limerock Base',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'Viviana Gabor',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.4',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 39,
        status: 0,
        jobsiteId: 1,
        jobsitename: 'Kelvingroove Park',
        jobsitecode: 'JSA',
        deliveryticket: '12390',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'Alina Costache',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.1',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 40,
        status: 1,
        jobsiteId: 1,
        jobsitename: 'Punta Estrella',
        jobsitecode: 'JSA',
        deliveryticket: '02101',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'Vlad Tudor',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.8',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      },
      {
        id: 41,
        status: 1,
        jobsiteId: 4,
        jobsitename: 'Stonecridge North',
        jobsitecode: 'JSD',
        deliveryticket: '02101',
        productname: '407 Rock',
        productcommercialcode: '300',
        ordernumber: '1-2000-231-123',
        hauler: 'Vlad Tudor',
        vehicle: '2VEH-100',
        receiver: 'Lucas Brava',
        quarry: "FEC Quarry, Glasgow",
        weightmaster: "CEMEX",
        deputyweightmaster: "Gino Viston",
        datecreated: 'Mon Feb 24 2020 00:00:00 GMT+0100 (Central European Standard Time)',
        quarryarrivaltime: 'Mon Feb 24 2020 14:30:00 GMT+0100 (Central European Standard Time)',
        quarrydeparturetime: 'Mon Feb 24 2020 15:00:00 GMT+0100 (Central European Standard Time)',
        signedtime: "Mon Feb 24 2020 13:00:00 GMT+0100 (Central European Standard Time)",
        unloadtime: 'Mon Feb 24 2020 13:30:00 GMT+0100 (Central European Standard Time)',
        quantity:'20.8',
        grossweight: '40',
        tareweight: '38',
        netweight: '35',
        dayloads: '12' 
      }
    ];

    const trucks: any[] = [
      {
        id:1,
        vehicle: '1VEH-100',
        hauler: 'Mike Doe',
        driver: 'Roberto Luna',
        driverstartdate: "Tue Jan 03 2017 13:00:00 GMT+0100 (Central European Standard Time)",
        driverphotopath: '../assets/images/driver-photo.png',
        totalvolume: 240,
        totalloads: 24,
        totalquantitycollected: 3000,
        totalloadsdelivered: 300,
        averagedeliverytime: 25,
        averagetimeinquarry: 20,
        mostvisitedquarry: 'FEC Quarry, Glasgow'
      },
      {
        id:2,
        vehicle: '2VEH-100',
        hauler: 'Mike Doe',
        driver: 'Mike Johnson',
        driverstartdate: "Tue Jan 03 2017 13:00:00 GMT+0100 (Central European Standard Time)",
        driverphotopath: '../assets/images/driver-photo-2.png',
        totalvolume: 320,
        totalloads: 32,
        totalquantitycollected: 4000,
        totalloadsdelivered: 400,
        averagedeliverytime: 30,
        averagetimeinquarry: 20,
        mostvisitedquarry: 'FEC Quarry, Glasgow'
      },
      {
        id:3,
        vehicle: '3VEH-100',
        hauler: 'Mike Doe',
        driver: 'Sam Timothy',
        driverstartdate: "Tue Jan 03 2017 13:00:00 GMT+0100 (Central European Standard Time)",
        driverphotopath: '../assets/images/driver-photo-3.png',
        totalvolume: 180,
        totalloads: 18,
        totalquantitycollected: 6200,
        totalloadsdelivered: 620,
        averagedeliverytime: 30,
        averagetimeinquarry: 20,
        mostvisitedquarry: 'FEC Quarry, Glasgow'
      },
      {
        id:4,
        vehicle: '4VEH-100',
        hauler: 'Mike Doe',
        driver: 'Morgan Frememan',
        driverstartdate: "Tue Jan 03 2017 13:00:00 GMT+0100 (Central European Standard Time)",
        driverphotopath: '../assets/images/driver-photo-4.png',
        totalvolume: 920,
        totalloads: 92,
        totalquantitycollected: 9000,
        totalloadsdelivered: 900,
        averagedeliverytime: 30,
        averagetimeinquarry: 20,
        mostvisitedquarry: 'FEC Quarry, Glasgow'
      }
    ];

    return { jobsites, plannings, planningstatuses, planningcolors, deliveries, deliverystatuses, statuscolor, trucks };
  }

  // Overrides the genId method to ensure that a hero always has an id.
  // If the heroes array is empty,
  // the method below returns the initial number (11).
  // if the heroes array is not empty, the method below returns the highest
  // hero id + 1.

  genId(jobsites): number {
    return jobsites.length > 0 ? Math.max(...jobsites.map(jobsite => jobsite.id)) + 1 : 1;
  }

  genPlanningId(plannings): number {
    return plannings.length > 0 ? Math.max(...plannings.map(planning => planning.id)) + 1 : 1;
  }

  genDeliveryId(deliveries): number {
    return deliveries.length > 0 ? Math.max(...deliveries.map(delivery => delivery.id)) + 1 : 1;
  }

  genTruckId(trucks): number {
    return trucks.length > 0 ? Math.max(...trucks.map(truck => truck.id)) + 1 : 1;
  }
}
